// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: complex_queries.sql

package db

import (
	"context"
	"database/sql"
)

const findInvalidTasks = `-- name: FindInvalidTasks :many
SELECT t.id, t.title, t.team_id, t.assignee_id
FROM tasks t
LEFT JOIN team_members tm ON t.team_id = tm.team_id AND t.assignee_id = tm.user_id
WHERE t.assignee_id IS NOT NULL 
  AND tm.user_id IS NULL
`

type FindInvalidTasksRow struct {
	ID         int64
	Title      string
	TeamID     int64
	AssigneeID sql.NullInt64
}

func (q *Queries) FindInvalidTasks(ctx context.Context) ([]FindInvalidTasksRow, error) {
	rows, err := q.db.QueryContext(ctx, findInvalidTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindInvalidTasksRow
	for rows.Next() {
		var i FindInvalidTasksRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.TeamID,
			&i.AssigneeID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTeamStats = `-- name: GetTeamStats :many
SELECT 
    t.name AS team_name,
    COUNT(DISTINCT tm.user_id) AS members_count,
    COUNT(DISTINCT task.id) AS done_tasks_last_7_days
FROM teams t
LEFT JOIN team_members tm ON t.id = tm.team_id
LEFT JOIN tasks task ON t.id = task.team_id 
    AND task.status = 'done' 
    AND task.updated_at >= NOW() - INTERVAL 7 DAY
GROUP BY t.id, t.name
`

type GetTeamStatsRow struct {
	TeamName           string
	MembersCount       int64
	DoneTasksLast7Days int64
}

func (q *Queries) GetTeamStats(ctx context.Context) ([]GetTeamStatsRow, error) {
	rows, err := q.db.QueryContext(ctx, getTeamStats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTeamStatsRow
	for rows.Next() {
		var i GetTeamStatsRow
		if err := rows.Scan(&i.TeamName, &i.MembersCount, &i.DoneTasksLast7Days); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopUsersPerTeam = `-- name: GetTopUsersPerTeam :many
SELECT 
    final_tab.team_id,
    final_tab.user_id,
    final_tab.task_count,
    final_tab.rank_num
FROM (
    SELECT 
        user_counts.team_id,
        user_counts.user_id,
        user_counts.task_count,
        DENSE_RANK() OVER (PARTITION BY user_counts.team_id ORDER BY user_counts.task_count DESC) as rank_num
    FROM (
        SELECT 
            team_id,
            created_by AS user_id,
            COUNT(*) AS task_count
        FROM tasks
        WHERE created_at >= NOW() - INTERVAL 1 MONTH
        GROUP BY team_id, created_by
    ) AS user_counts
) AS final_tab
WHERE final_tab.rank_num <= 3
`

type GetTopUsersPerTeamRow struct {
	TeamID    int64
	UserID    int64
	TaskCount int64
	RankNum   interface{}
}

func (q *Queries) GetTopUsersPerTeam(ctx context.Context) ([]GetTopUsersPerTeamRow, error) {
	rows, err := q.db.QueryContext(ctx, getTopUsersPerTeam)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTopUsersPerTeamRow
	for rows.Next() {
		var i GetTopUsersPerTeamRow
		if err := rows.Scan(
			&i.TeamID,
			&i.UserID,
			&i.TaskCount,
			&i.RankNum,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
