// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
)

type TasksStatus string

const (
	TasksStatusTodo       TasksStatus = "todo"
	TasksStatusInProgress TasksStatus = "in_progress"
	TasksStatusDone       TasksStatus = "done"
)

func (e *TasksStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TasksStatus(s)
	case string:
		*e = TasksStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TasksStatus: %T", src)
	}
	return nil
}

type NullTasksStatus struct {
	TasksStatus TasksStatus
	Valid       bool // Valid is true if TasksStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTasksStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TasksStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TasksStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTasksStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TasksStatus), nil
}

type TeamMembersRole string

const (
	TeamMembersRoleOwner  TeamMembersRole = "owner"
	TeamMembersRoleAdmin  TeamMembersRole = "admin"
	TeamMembersRoleMember TeamMembersRole = "member"
)

func (e *TeamMembersRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TeamMembersRole(s)
	case string:
		*e = TeamMembersRole(s)
	default:
		return fmt.Errorf("unsupported scan type for TeamMembersRole: %T", src)
	}
	return nil
}

type NullTeamMembersRole struct {
	TeamMembersRole TeamMembersRole
	Valid           bool // Valid is true if TeamMembersRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTeamMembersRole) Scan(value interface{}) error {
	if value == nil {
		ns.TeamMembersRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TeamMembersRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTeamMembersRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TeamMembersRole), nil
}

type Task struct {
	ID          int64
	Title       string
	Description sql.NullString
	Status      TasksStatus
	TeamID      int64
	AssigneeID  sql.NullInt64
	CreatedBy   int64
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

type TaskComment struct {
	ID        int64
	TaskID    int64
	UserID    int64
	Content   string
	CreatedAt sql.NullTime
}

type TaskHistory struct {
	ID         int64
	TaskID     int64
	ChangedBy  sql.NullInt64
	ChangeType string
	OldValue   sql.NullString
	NewValue   sql.NullString
	CreatedAt  sql.NullTime
}

type Team struct {
	ID        int64
	Name      string
	CreatedBy int64
	CreatedAt sql.NullTime
}

type TeamMember struct {
	TeamID   int64
	UserID   int64
	Role     TeamMembersRole
	JoinedAt sql.NullTime
}

type User struct {
	ID           int64
	Email        string
	PasswordHash string
	CreatedAt    sql.NullTime
}
