// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: task_history.sql

package db

import (
	"context"
	"database/sql"
)

const createTaskComment = `-- name: CreateTaskComment :execresult
INSERT INTO task_comments (task_id, user_id, content)
VALUES (?, ?, ?)
`

type CreateTaskCommentParams struct {
	TaskID  int64
	UserID  int64
	Content string
}

func (q *Queries) CreateTaskComment(ctx context.Context, arg CreateTaskCommentParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createTaskComment, arg.TaskID, arg.UserID, arg.Content)
}

const createTaskHistory = `-- name: CreateTaskHistory :exec
INSERT INTO task_history (task_id, changed_by, change_type, old_value, new_value)
VALUES (?, ?, ?, ?, ?)
`

type CreateTaskHistoryParams struct {
	TaskID     int64
	ChangedBy  sql.NullInt64
	ChangeType string
	OldValue   sql.NullString
	NewValue   sql.NullString
}

func (q *Queries) CreateTaskHistory(ctx context.Context, arg CreateTaskHistoryParams) error {
	_, err := q.db.ExecContext(ctx, createTaskHistory,
		arg.TaskID,
		arg.ChangedBy,
		arg.ChangeType,
		arg.OldValue,
		arg.NewValue,
	)
	return err
}

const listTaskComments = `-- name: ListTaskComments :many
SELECT tc.id, tc.task_id, tc.user_id, tc.content, tc.created_at, u.email as user_email
FROM task_comments tc
JOIN users u ON tc.user_id = u.id
WHERE tc.task_id = ?
ORDER BY tc.created_at ASC
`

type ListTaskCommentsRow struct {
	ID        int64
	TaskID    int64
	UserID    int64
	Content   string
	CreatedAt sql.NullTime
	UserEmail string
}

func (q *Queries) ListTaskComments(ctx context.Context, taskID int64) ([]ListTaskCommentsRow, error) {
	rows, err := q.db.QueryContext(ctx, listTaskComments, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTaskCommentsRow
	for rows.Next() {
		var i ListTaskCommentsRow
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.UserID,
			&i.Content,
			&i.CreatedAt,
			&i.UserEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskHistory = `-- name: ListTaskHistory :many
SELECT th.id, th.task_id, th.changed_by, th.change_type, th.old_value, th.new_value, th.created_at, u.email as user_email
FROM task_history th
LEFT JOIN users u ON th.changed_by = u.id
WHERE th.task_id = ?
ORDER BY th.created_at DESC
`

type ListTaskHistoryRow struct {
	ID         int64
	TaskID     int64
	ChangedBy  sql.NullInt64
	ChangeType string
	OldValue   sql.NullString
	NewValue   sql.NullString
	CreatedAt  sql.NullTime
	UserEmail  sql.NullString
}

func (q *Queries) ListTaskHistory(ctx context.Context, taskID int64) ([]ListTaskHistoryRow, error) {
	rows, err := q.db.QueryContext(ctx, listTaskHistory, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTaskHistoryRow
	for rows.Next() {
		var i ListTaskHistoryRow
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.ChangedBy,
			&i.ChangeType,
			&i.OldValue,
			&i.NewValue,
			&i.CreatedAt,
			&i.UserEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
