// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: tasks.sql

package db

import (
	"context"
	"database/sql"
)

const createTask = `-- name: CreateTask :execresult
INSERT INTO tasks (title, description, status, team_id, assignee_id, created_by) 
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateTaskParams struct {
	Title       string
	Description sql.NullString
	Status      TasksStatus
	TeamID      int64
	AssigneeID  sql.NullInt64
	CreatedBy   int64
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createTask,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.TeamID,
		arg.AssigneeID,
		arg.CreatedBy,
	)
}

const deleteTask = `-- name: DeleteTask :exec
DELETE FROM tasks WHERE id = ?
`

func (q *Queries) DeleteTask(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTask, id)
	return err
}

const getTaskByID = `-- name: GetTaskByID :one
SELECT id, title, description, status, team_id, assignee_id, created_by, created_at, updated_at FROM tasks 
WHERE id = ? LIMIT 1
`

func (q *Queries) GetTaskByID(ctx context.Context, id int64) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTaskByID, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.TeamID,
		&i.AssigneeID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTasks = `-- name: ListTasks :many
SELECT id, title, description, status, team_id, assignee_id, created_by, created_at, updated_at FROM tasks
WHERE 
    team_id = ?
    AND (? IS NULL OR status = ?)
    AND (? IS NULL OR assignee_id = ?)
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListTasksParams struct {
	TeamID     int64
	Status     NullTasksStatus
	AssigneeID sql.NullInt64
	Limit      int32
	Offset     int32
}

func (q *Queries) ListTasks(ctx context.Context, arg ListTasksParams) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasks,
		arg.TeamID,
		arg.Status,
		arg.Status,
		arg.AssigneeID,
		arg.AssigneeID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.TeamID,
			&i.AssigneeID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTask = `-- name: UpdateTask :exec
UPDATE tasks 
SET title = ?, description = ?, status = ?, assignee_id = ? 
WHERE id = ?
`

type UpdateTaskParams struct {
	Title       string
	Description sql.NullString
	Status      TasksStatus
	AssigneeID  sql.NullInt64
	ID          int64
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) error {
	_, err := q.db.ExecContext(ctx, updateTask,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.AssigneeID,
		arg.ID,
	)
	return err
}
