// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: teams.sql

package db

import (
	"context"
	"database/sql"
)

const addTeamMember = `-- name: AddTeamMember :exec
INSERT INTO team_members (team_id, user_id, role) 
VALUES (?, ?, ?)
`

type AddTeamMemberParams struct {
	TeamID int64
	UserID int64
	Role   TeamMembersRole
}

func (q *Queries) AddTeamMember(ctx context.Context, arg AddTeamMemberParams) error {
	_, err := q.db.ExecContext(ctx, addTeamMember, arg.TeamID, arg.UserID, arg.Role)
	return err
}

const createTeam = `-- name: CreateTeam :execresult
INSERT INTO teams (name, created_by) 
VALUES (?, ?)
`

type CreateTeamParams struct {
	Name      string
	CreatedBy int64
}

func (q *Queries) CreateTeam(ctx context.Context, arg CreateTeamParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createTeam, arg.Name, arg.CreatedBy)
}

const getTeamByID = `-- name: GetTeamByID :one
SELECT id, name, created_by, created_at FROM teams 
WHERE id = ? LIMIT 1
`

func (q *Queries) GetTeamByID(ctx context.Context, id int64) (Team, error) {
	row := q.db.QueryRowContext(ctx, getTeamByID, id)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getUserRoleInTeam = `-- name: GetUserRoleInTeam :one
SELECT role FROM team_members 
WHERE team_id = ? AND user_id = ?
`

type GetUserRoleInTeamParams struct {
	TeamID int64
	UserID int64
}

func (q *Queries) GetUserRoleInTeam(ctx context.Context, arg GetUserRoleInTeamParams) (TeamMembersRole, error) {
	row := q.db.QueryRowContext(ctx, getUserRoleInTeam, arg.TeamID, arg.UserID)
	var role TeamMembersRole
	err := row.Scan(&role)
	return role, err
}

const listUserTeams = `-- name: ListUserTeams :many
SELECT t.id, t.name, t.created_by, t.created_at, tm.role 
FROM teams t
JOIN team_members tm ON t.id = tm.team_id
WHERE tm.user_id = ?
`

type ListUserTeamsRow struct {
	ID        int64
	Name      string
	CreatedBy int64
	CreatedAt sql.NullTime
	Role      TeamMembersRole
}

func (q *Queries) ListUserTeams(ctx context.Context, userID int64) ([]ListUserTeamsRow, error) {
	rows, err := q.db.QueryContext(ctx, listUserTeams, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserTeamsRow
	for rows.Next() {
		var i ListUserTeamsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
